### ISSUE TITLE
entities state class 'measurement' but 'last_reset' is missing

### ISSUE THREAD

**Issue by muppet99** [kloknibor/MasterVoltXS#3]
Appearantly some things changed in homeassistant since updates of feb. Currently the sensor state class is measurement of sensor.wtot_solar. This should be changed to total_increasing, so it doesn't need a reset date/time.

[Sensor Entity](https://developers.home-assistant.io/docs/core/entity/sensor/)

**Comment by spleijers** [comment]
Unfortunately no reply on this....  I can share how i made some custom sensor to fix that:

```
 - sensor:          
      - name: "Imported Power Yearly kWh MasterVoltXS"
        unique_id: mastervolt_imported_power_yearly_kwh
        device_class: energy  
        state_class: total_increasing
        unit_of_measurement: 'kWh'
        availability: >
          {% if is_state("sensor.wtot_solar", "unavailable") %}
            false
          {% elif is_state("sensor.wtot_solar", "unknown") %}
            false
          {% else %}
            true
          {%- endif %}
        state: "{{ ( ((states.sensor.wtot_solar.state | float) - (states('input_number.zonnepanelen_jaar_startwaarde') | float)) ) | round(2) }}"
        last_reset: '{{ now().year }}-00-00T00:00:00+00:00'


input_number:
  zonnepanelen_jaar_startwaarde:
    name: Zonnepanelen jaar startwaarde
    unit_of_measurement: "kWh"
    #initial: 22889
    min: 22889
    max: 32889
    step: 1
    mode: box
```

This seems to be working for me. But no guarantees, and you will have to setup the yearly 'start value' of the solar power production.
